import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Fetches the site's two typefaces for self-hosting. §19.10, §14.6
 *
 *   node scripts/data/fonts.ts
 *
 * Run this only when the fonts need refreshing — the files it writes are
 * committed, so an ordinary build and CI never touch the network.
 *
 * Both families are requested as **variable** fonts (a `..` range rather than a
 * list of weights), which is one file per style instead of one per weight, and
 * lets the design use any weight in the range later without another download.
 *
 * Only the `latin` and `latin-ext` subsets are kept. The site is written in
 * English and reaches into Latin diacritics for dish names — "Margherita",
 * "Pecorino", "Zaʼatar" — and nothing on it is Cyrillic, Greek or Vietnamese.
 * The `unicode-range` on each face means a reader only ever downloads the
 * subset their page actually needs.
 */

const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:ital,opsz,wght@0,9..144,300..600;1,9..144,400..500' +
  '&family=Inter:wght@400..600' +
  '&display=swap';

/* Google serves woff2 only to browsers it recognises; anything else gets ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const KEEP = new Set(['latin', 'latin-ext']);
const OUT = 'src/assets/fonts';

const FACE = /\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]+)\}/g;
const field = (body: string, name: string): string =>
  body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim() ?? '';

async function run(): Promise<void> {
  const css = await fetch(GOOGLE_CSS, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
    return r.text();
  });

  await mkdir(OUT, { recursive: true });
  const rules: string[] = [];

  for (const [, subset = '', body = ''] of css.matchAll(FACE)) {
    if (!KEEP.has(subset)) continue;

    const family = field(body, 'font-family').replace(/'/g, '');
    const style = field(body, 'font-style');
    const weight = field(body, 'font-weight');
    const range = field(body, 'unicode-range');
    const url = body.match(/url\((https[^)]+)\)/)?.[1];
    if (!url) continue;

    const name = `${family.toLowerCase()}-${style}-${subset}.woff2`;
    const downloaded = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) =>
      r.arrayBuffer(),
    );
    const bytes = Buffer.from(new Uint8Array(downloaded));
    await writeFile(path.join(OUT, name), bytes);
    console.log(`${name.padEnd(34)} ${(bytes.length / 1024).toFixed(1)} KB`);

    rules.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('../assets/fonts/${name}') format('woff2');`,
        `  unicode-range: ${range};`,
        '}',
      ].join('\n'),
    );
  }

  const header = [
    '/*',
    ' * Self-hosted, generated by scripts/data/fonts.ts. Do not edit by hand.',
    ' *',
    ' * Referenced through `../assets/` rather than `public/` so the bundler',
    ' * rewrites and hashes the URLs — which keeps them correct whatever the',
    ' * deployment base path is, and lets them be cached forever.',
    ' */',
    '',
  ].join('\n');

  await writeFile('src/styles/fonts.css', `${header}${rules.join('\n\n')}\n`);
  console.log(`\n${rules.length} face(s) written to src/styles/fonts.css`);
}

await run();
